In [2]:
!pip install pandas

Collecting pandas
  Downloading pandas-3.0.2-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.4.4-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.2-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (10.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 23.6 MB/s  0:00:00m0:00:010:01
Downloading numpy-2.4.4-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 47.7 MB/s  0:00:006m0:00:01
Installing collected packages: numpy, pandas
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [pandas]2m1/2 [pandas]
Successfully installed numpy-2.4.4 pandas-3.0.2

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

In [4]:
import pandas as pd
import numpy as np

# Set a random seed for reproducibility
np.random.seed(42) # You can use any integer value here. For quiz put 42

# Generate 25 random names for the 'nombre' column
nombres = [f'Estudiante{i}' for i in range(10)]

# Generate 4 columns of random grades between 0 and 5 with two decimal places
# np.random.uniform generates floats between low (inclusive) and high (exclusive)
parciales = np.round(np.random.uniform(0, 5, size=(10, 4)), 2);

# Create the DataFrame
df = pd.DataFrame({
    'nombre': nombres,
    'parcial1': parciales[:, 0],
    'parcial2': parciales[:, 1],
    'parcial3': parciales[:, 2],
    'parcial4': parciales[:, 3]
})

df

        nombre  parcial1  parcial2  parcial3  parcial4
0  Estudiante0      1.87      4.75      3.66      2.99
1  Estudiante1      0.78      0.78      0.29      4.33
2  Estudiante2      3.01      3.54      0.10      4.85
3  Estudiante3      4.16      1.06      0.91      0.92
4  Estudiante4      1.52      2.62      2.16      1.46
5  Estudiante5      3.06      0.70      1.46      1.83
6  Estudiante6      2.28      3.93      1.00      2.57
7  Estudiante7      2.96      0.23      3.04      0.85
8  Estudiante8      0.33      4.74      4.83      4.04
9  Estudiante9      1.52      0.49      3.42      2.20

In [6]:
df['Notafinal'] = 0.2*df['parcial1'] + 0.2*df['parcial2'] + 0.2*df['parcial3'] + 0.4*df['parcial4']
df

        nombre  parcial1  parcial2  parcial3  parcial4  Notafinal
0  Estudiante0      1.87      4.75      3.66      2.99      3.252
1  Estudiante1      0.78      0.78      0.29      4.33      2.102
2  Estudiante2      3.01      3.54      0.10      4.85      3.270
3  Estudiante3      4.16      1.06      0.91      0.92      1.594
4  Estudiante4      1.52      2.62      2.16      1.46      1.844
5  Estudiante5      3.06      0.70      1.46      1.83      1.776
6  Estudiante6      2.28      3.93      1.00      2.57      2.470
7  Estudiante7      2.96      0.23      3.04      0.85      1.586
8  Estudiante8      0.33      4.74      4.83      4.04      3.596
9  Estudiante9      1.52      0.49      3.42      2.20      1.966

In [30]:
def aprobado(dataframe):
    dataframe['Notafinal'] = 0.2*dataframe['parcial1'] + 0.2*dataframe['parcial2'] + 0.2*dataframe['parcial3'] + 0.4*dataframe['parcial4'] 
    cont = 0
    for i in range(df.shape[0]):
        if dataframe.iloc[i,5] >= 3.75:
            cont += 1
    return cont

In [31]:
aprobado(df)

0

In [25]:
df.shape

(10, 6)